Data: 
    path:
        - ['/home/verf/WorkSpace/Data', 'ps']
    load_rate: 50000

Model:
    input_size: 100
    hidden_size: 128
    num_layers: 2
    num_classes: 2
    batch_size: 128
    num_epochs: 5
    dropout: 0.2
    learning_rate: 0.01

